-- Auditoria de leitura: quem abriu o detalhe de um caso (GET /api/fichas/{id}).
-- Aditivo e idempotente: pode rodar em bancos que já existem (local, Supabase, produção) sem apagar dados.
-- Rodar como o dono do banco (em produção, azizaid_owner), para a azizaid_app herdar os grants.
-- Rodar ANTES de mergear o PR que traz este script (auto-deploy do Render a partir de main)
-- e, em produção, antes do deploy da tag.
-- Nunca rodar db/01_schema.sql para aplicar esta mudança: ele começa com DROP TABLE ... CASCADE.

CREATE TABLE IF NOT EXISTS leitura_audit_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ficha_id         BIGINT      NOT NULL,
    profissional_id  BIGINT      NOT NULL,
    timestamp        TIMESTAMP   NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_leitura_audit_log_ficha ON leitura_audit_log (ficha_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_leitura_audit_log_profissional_ficha ON leitura_audit_log (profissional_id, ficha_id, timestamp);
