-- Gestão de usuários: username, email opcional, flag de gerenciador, troca de senha obrigatória,
-- profissional_id no auth_audit_log e a trilha conta_audit_log.
-- Aditivo e idempotente: pode rodar em bancos que já existem (local, Supabase, produção) sem apagar dados.
-- Rodar ANTES de mergear o PR que traz este script (auto-deploy do Render a partir de main).
-- Nunca rodar db/01_schema.sql para aplicar esta mudança: ele começa com DROP TABLE ... CASCADE.
-- No psql, rodar com -v ON_ERROR_STOP=1. Tudo numa transação: se algo falhar (ex.: dois emails
-- que só diferem em maiúsculas/minúsculas colidem no lower()), nada fica aplicado pela metade.

BEGIN;

ALTER TABLE profissional ADD COLUMN IF NOT EXISTS username VARCHAR(30);
ALTER TABLE profissional ADD COLUMN IF NOT EXISTS pode_gerenciar_profissionais BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE profissional ADD COLUMN IF NOT EXISTS deve_trocar_senha BOOLEAN NOT NULL DEFAULT FALSE;

-- Username das contas existentes: a parte antes do @ do email, só com os caracteres permitidos.
UPDATE profissional
   SET username = left(lower(regexp_replace(split_part(email, '@', 1), '[^a-zA-Z0-9._-]', '', 'g')), 30)
 WHERE username IS NULL;
-- Curtos demais ou repetidos ganham o id no fim (vazio vira "usuario.<id>").
UPDATE profissional p
   SET username = left(coalesce(nullif(p.username, ''), 'usuario'), 20) || '.' || p.id
 WHERE length(p.username) < 3
    OR EXISTS (SELECT 1 FROM profissional o WHERE o.username = p.username AND o.id < p.id);

ALTER TABLE profissional ALTER COLUMN username SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_profissional_username ON profissional (username);

-- Colisão aqui viola o UNIQUE de email e aborta o script: resolver à mão antes de rodar de novo.
UPDATE profissional SET email = lower(trim(email)) WHERE email IS NOT NULL AND email <> lower(trim(email));
ALTER TABLE profissional ALTER COLUMN email DROP NOT NULL;

ALTER TABLE auth_audit_log ADD COLUMN IF NOT EXISTS profissional_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_auth_audit_log_profissional_timestamp ON auth_audit_log (profissional_id, timestamp);

CREATE TABLE IF NOT EXISTS conta_audit_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profissional_id  BIGINT       NOT NULL,
    autor_id         BIGINT       NOT NULL,
    acao             VARCHAR(40)  NOT NULL,
    detalhe          VARCHAR(300),
    timestamp        TIMESTAMP    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_conta_audit_log_profissional ON conta_audit_log (profissional_id, timestamp);

COMMIT;
