DROP TABLE IF EXISTS entity_audit_log             CASCADE;
DROP TABLE IF EXISTS auth_audit_log               CASCADE;
DROP TABLE IF EXISTS ficha_necessidade_imediata   CASCADE;
DROP TABLE IF EXISTS ficha_vaga_necessaria        CASCADE;
DROP TABLE IF EXISTS acolhimento_tipo_violencia   CASCADE;
DROP TABLE IF EXISTS acolhimento_equipe           CASCADE;
DROP TABLE IF EXISTS historico_atendimento        CASCADE;
DROP TABLE IF EXISTS avaliacao_socioeconomica     CASCADE;
DROP TABLE IF EXISTS interacao        CASCADE;
DROP TABLE IF EXISTS encaminhamento   CASCADE;
DROP TABLE IF EXISTS profissional     CASCADE;
DROP TABLE IF EXISTS servico          CASCADE;
DROP TABLE IF EXISTS ficha            CASCADE;

CREATE TABLE ficha (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_ficha         VARCHAR(20)  NOT NULL UNIQUE,
    numero_caso          VARCHAR(30)  NOT NULL,
    nome                 VARCHAR(150) NOT NULL,
    cpf                  VARCHAR(14)  NOT NULL,
    idade                INTEGER,
    telefone             VARCHAR(20),
    estado_civil         VARCHAR(40),
    pessoas_dependentes  INTEGER,
    idade_filhos         VARCHAR(120),
    nivel_seguranca      INTEGER,
    tipo_moradia         VARCHAR(20)
        CONSTRAINT ck_ficha_tipo_moradia
        CHECK (tipo_moradia IN ('CASA_PROPRIA', 'ALUGADA', 'CEDIDA', 'ABRIGO', 'OUTRO')),
    tipo_moradia_outra_descricao VARCHAR(150),
    qtd_moradores        INTEGER,
    qtd_filhos           INTEGER,
    onde_moram_filhos   VARCHAR(30)
        CONSTRAINT ck_ficha_onde_moram_filhos
        CHECK (onde_moram_filhos IN ('COMIGO', 'COM_FAMILIARES_AMIGOS', 'ABRIGO_INSTITUCIONAL', 'SOZINHO_CONJUGE', 'NAO_TEM_FILHOS')),
    supervisao_filhos   VARCHAR(20)
        CONSTRAINT ck_ficha_supervisao_filhos
        CHECK (supervisao_filhos IN ('SIM', 'NAO', 'NAO_PRECISA')),
    necessidade_outra_descricao VARCHAR(200),
    data_criacao         TIMESTAMP    NOT NULL,
    data_atualizacao     TIMESTAMP    NOT NULL,
    status               VARCHAR(10)  NOT NULL
        CONSTRAINT ck_ficha_status
        CHECK (status IN ('ATIVO', 'INATIVO')),
    criado_por_id        BIGINT,
    ultimo_editor_id     BIGINT
);

CREATE TABLE ficha_vaga_necessaria (
    ficha_id          BIGINT      NOT NULL,
    vaga_necessaria   VARCHAR(30) NOT NULL
        CONSTRAINT ck_vaga_necessaria
        CHECK (vaga_necessaria IN ('CRECHE', 'ESCOLA', 'ATENDIMENTO_PSICOSSOCIAL', 'NAO_PRECISA')),
    CONSTRAINT fk_ficha_vaga_necessaria_ficha
        FOREIGN KEY (ficha_id) REFERENCES ficha (id) ON DELETE CASCADE
);

CREATE TABLE ficha_necessidade_imediata (
    ficha_id              BIGINT      NOT NULL,
    necessidade_imediata  VARCHAR(40) NOT NULL
        CONSTRAINT ck_necessidade_imediata
        CHECK (necessidade_imediata IN ('INFORMACOES_DIREITOS', 'ATENDIMENTO_SAUDE', 'APOIO_PSICOLOGICO',
            'ATENDIMENTO_ASSISTENCIA_SOCIAL', 'APOIO_MORADIA', 'APOIO_TRABALHO', 'OUTRO')),
    CONSTRAINT fk_ficha_necessidade_imediata_ficha
        FOREIGN KEY (ficha_id) REFERENCES ficha (id) ON DELETE CASCADE
);

CREATE TABLE avaliacao_socioeconomica (
    id                                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ficha_id                               BIGINT NOT NULL UNIQUE,

    tem_renda                              BOOLEAN,
    valor_renda                            NUMERIC(10,2),
    pessoas_dependem_renda                 INTEGER,
    origem_renda                           VARCHAR(200),
    trabalho_formal                        BOOLEAN,
    renda_suficiente                       BOOLEAN,

    trabalhando_atualmente                 BOOLEAN,
    onde_trabalha                          VARCHAR(200),
    problema_saude_atrapalha_trabalho      BOOLEAN,
    problema_saude_qual                    VARCHAR(200),
    situacao_familiar_atrapalha_trabalho   BOOLEAN,
    situacao_familiar_qual                 VARCHAR(200),
    deseja_trabalhar                       BOOLEAN,
    periodo_desejado                       VARCHAR(20)
        CONSTRAINT ck_avaliacao_periodo_desejado
        CHECK (periodo_desejado IN ('DIA', 'NOITE', 'MEIO_PERIODO')),

    sabe_ler                               BOOLEAN,
    nivel_escrita                          VARCHAR(20)
        CONSTRAINT ck_avaliacao_nivel_escrita
        CHECK (nivel_escrita IN ('NAO', 'SO_NOME', 'SIM')),
    nivel_escolaridade                     VARCHAR(20)
        CONSTRAINT ck_avaliacao_nivel_escolaridade
        CHECK (nivel_escolaridade IN ('NAO_ESTUDOU', 'FUNDAMENTAL', 'MEDIO', 'TECNICO', 'FACULDADE')),
    escolaridade_detalhe                   VARCHAR(150),
    fez_curso_profissionalizante           BOOLEAN,
    curso_profissionalizante_qual          VARCHAR(200),
    deseja_auxilio_ceebja                  BOOLEAN,
    deseja_curso_senai                     BOOLEAN,
    area_curso_senai                       VARCHAR(150),

    tem_rede_apoio                         BOOLEAN,
    precisa_ajuda_moradia                  BOOLEAN,
    tem_o_que_comer                        BOOLEAN,

    acompanhamento_medico                  BOOLEAN,
    precisa_ajuda_tratamento_medico        BOOLEAN,
    uso_continuo_medicamento               BOOLEAN,
    medicamento_quais                      VARCHAR(300),
    acesso_medicamentos                    BOOLEAN,

    criado_por_id                          BIGINT,
    ultimo_editor_id                       BIGINT,

    CONSTRAINT fk_avaliacao_socioeconomica_ficha
        FOREIGN KEY (ficha_id) REFERENCES ficha (id) ON DELETE CASCADE
);

CREATE TABLE historico_atendimento (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ficha_id                        BIGINT NOT NULL UNIQUE,
    ja_procurou_servico             BOOLEAN,
    servico_procurado_qual_onde     VARCHAR(300),
    em_fila_espera                  BOOLEAN,
    fila_espera_qual                VARCHAR(200),
    ja_pediu_ajuda_justica_policia  BOOLEAN,
    justica_policia_qual            VARCHAR(200),
    como_foi_atendimento            VARCHAR(1000),
    resolveu_situacao               BOOLEAN,
    reacao_agressor                 VARCHAR(500),
    criado_por_id                   BIGINT,
    ultimo_editor_id                BIGINT,
    CONSTRAINT fk_historico_atendimento_ficha
        FOREIGN KEY (ficha_id) REFERENCES ficha (id) ON DELETE CASCADE
);

CREATE TABLE acolhimento_equipe (
    id                                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ficha_id                                    BIGINT NOT NULL UNIQUE,

    numero_processo_mpu                         VARCHAR(40),
    data_reuniao_acolhimento                    DATE,
    servidor_responsavel                        VARCHAR(150),

    tipo_violencia_outra_descricao              VARCHAR(200),
    frequencia_violencia                        VARCHAR(20)
        CONSTRAINT ck_acolhimento_frequencia_violencia
        CHECK (frequencia_violencia IN ('EPISODIO_UNICO', 'RECORRENTE')),
    medidas_protetivas_anteriores               BOOLEAN,
    ameacas_relatadas                           VARCHAR(1000),

    necessidade_atendimento_medico_imediato     BOOLEAN,
    acompanhamento_saude_mental_em_curso        BOOLEAN,
    acompanhamento_saude_mental_local           VARCHAR(150),

    dependente_sofreu_violencia                 BOOLEAN,
    dependente_precisa_auxilio_medico           BOOLEAN,

    categoria_classificacao                     VARCHAR(15)
        CONSTRAINT ck_acolhimento_categoria_classificacao
        CHECK (categoria_classificacao IN ('CATEGORIA_1', 'CATEGORIA_2', 'CATEGORIA_3', 'CATEGORIA_4')),

    observacoes_relevantes                      VARCHAR(2000),
    responsavel_acolhimento_juridico            VARCHAR(150),

    criado_por_id                               BIGINT,
    ultimo_editor_id                            BIGINT,

    CONSTRAINT fk_acolhimento_equipe_ficha
        FOREIGN KEY (ficha_id) REFERENCES ficha (id) ON DELETE CASCADE
);

CREATE TABLE acolhimento_tipo_violencia (
    acolhimento_id  BIGINT      NOT NULL,
    tipo_violencia  VARCHAR(20) NOT NULL
        CONSTRAINT ck_tipo_violencia
        CHECK (tipo_violencia IN ('FISICA', 'PSICOLOGICA', 'MORAL', 'PATRIMONIAL', 'OUTRA')),
    CONSTRAINT fk_acolhimento_tipo_violencia_acolhimento
        FOREIGN KEY (acolhimento_id) REFERENCES acolhimento_equipe (id) ON DELETE CASCADE
);

CREATE TABLE servico (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome   VARCHAR(100) NOT NULL
);

CREATE TABLE profissional (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                   VARCHAR(150) NOT NULL,
    cpf                    VARCHAR(14)  NOT NULL,
    carteira_profissional  VARCHAR(40),
    servico_id             BIGINT,
    email                  VARCHAR(150) NOT NULL UNIQUE,
    senha_hash             VARCHAR(100) NOT NULL,
    role                   VARCHAR(20)  NOT NULL DEFAULT 'PADRAO'
        CONSTRAINT ck_profissional_role
        CHECK (role IN ('DEV', 'PADRAO', 'ESTAGIARIO')),
    CONSTRAINT fk_profissional_servico
        FOREIGN KEY (servico_id) REFERENCES servico (id)
);

CREATE TABLE encaminhamento (
                                id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                ficha_id             BIGINT       NOT NULL,
                                servico_id           BIGINT       NOT NULL,
                                categoria            VARCHAR(30)
                                    CONSTRAINT ck_encaminhamento_categoria
                                    CHECK (categoria IN ('SAUDE_GERAL', 'SAUDE_MENTAL', 'HABITACAO',
                                        'TRABALHO_EMPREGO', 'ASSISTENCIA_SOCIAL', 'ASSISTENCIA_EDUCACIONAL', 'OUTRO')),
                                profissional         VARCHAR(150),
                                data_encaminhamento  DATE,
                                data_retorno         DATE,
                                descricao            VARCHAR(1000),
                                criado_por_id        BIGINT,
                                ultimo_editor_id     BIGINT,
                                CONSTRAINT fk_encaminhamento_ficha
                                    FOREIGN KEY (ficha_id) REFERENCES ficha (id) ON DELETE CASCADE,
                                CONSTRAINT fk_encaminhamento_servico
                                    FOREIGN KEY (servico_id) REFERENCES servico (id)
);

CREATE TABLE interacao (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ficha_id        BIGINT        NOT NULL,
    autor           VARCHAR(150),
    data_interacao  TIMESTAMP     NOT NULL,
    texto           VARCHAR(2000),
    criado_por_id   BIGINT,
    ultimo_editor_id BIGINT,
    CONSTRAINT fk_interacao_ficha
        FOREIGN KEY (ficha_id) REFERENCES ficha (id) ON DELETE CASCADE
);

CREATE TABLE auth_audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_tentado  VARCHAR(150) NOT NULL,
    sucesso        BOOLEAN      NOT NULL,
    timestamp      TIMESTAMP    NOT NULL,
    ip_address     VARCHAR(45),
    motivo_falha   VARCHAR(100)
);

CREATE TABLE entity_audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_entidade  VARCHAR(60)  NOT NULL,
    entidade_id    BIGINT       NOT NULL,
    editor_id      BIGINT       NOT NULL,
    dono_id        BIGINT       NOT NULL,
    timestamp      TIMESTAMP    NOT NULL,
    resumo         VARCHAR(300),
    CONSTRAINT fk_entity_audit_log_editor
        FOREIGN KEY (editor_id) REFERENCES profissional (id),
    CONSTRAINT fk_entity_audit_log_dono
        FOREIGN KEY (dono_id) REFERENCES profissional (id)
);

ALTER TABLE ficha                    ADD CONSTRAINT fk_ficha_criado_por                   FOREIGN KEY (criado_por_id) REFERENCES profissional (id);
ALTER TABLE ficha                    ADD CONSTRAINT fk_ficha_ultimo_editor                FOREIGN KEY (ultimo_editor_id) REFERENCES profissional (id);
ALTER TABLE avaliacao_socioeconomica ADD CONSTRAINT fk_avaliacao_criado_por               FOREIGN KEY (criado_por_id) REFERENCES profissional (id);
ALTER TABLE avaliacao_socioeconomica ADD CONSTRAINT fk_avaliacao_ultimo_editor            FOREIGN KEY (ultimo_editor_id) REFERENCES profissional (id);
ALTER TABLE historico_atendimento    ADD CONSTRAINT fk_historico_criado_por               FOREIGN KEY (criado_por_id) REFERENCES profissional (id);
ALTER TABLE historico_atendimento    ADD CONSTRAINT fk_historico_ultimo_editor            FOREIGN KEY (ultimo_editor_id) REFERENCES profissional (id);
ALTER TABLE acolhimento_equipe       ADD CONSTRAINT fk_acolhimento_criado_por             FOREIGN KEY (criado_por_id) REFERENCES profissional (id);
ALTER TABLE acolhimento_equipe       ADD CONSTRAINT fk_acolhimento_ultimo_editor          FOREIGN KEY (ultimo_editor_id) REFERENCES profissional (id);
ALTER TABLE encaminhamento           ADD CONSTRAINT fk_encaminhamento_criado_por          FOREIGN KEY (criado_por_id) REFERENCES profissional (id);
ALTER TABLE encaminhamento           ADD CONSTRAINT fk_encaminhamento_ultimo_editor       FOREIGN KEY (ultimo_editor_id) REFERENCES profissional (id);
ALTER TABLE interacao                ADD CONSTRAINT fk_interacao_criado_por               FOREIGN KEY (criado_por_id) REFERENCES profissional (id);
ALTER TABLE interacao                ADD CONSTRAINT fk_interacao_ultimo_editor            FOREIGN KEY (ultimo_editor_id) REFERENCES profissional (id);

CREATE INDEX idx_ficha_status            ON ficha (status);
CREATE INDEX idx_ficha_data_criacao      ON ficha (data_criacao);
CREATE INDEX idx_ficha_data_atualizacao  ON ficha (data_atualizacao);
CREATE INDEX idx_encaminhamento_ficha    ON encaminhamento (ficha_id);
CREATE INDEX idx_encaminhamento_servico ON encaminhamento (servico_id);
CREATE INDEX idx_interacao_ficha         ON interacao (ficha_id);
CREATE INDEX idx_profissional_servico    ON profissional (servico_id);
CREATE INDEX idx_ficha_vaga_necessaria_ficha        ON ficha_vaga_necessaria (ficha_id);
CREATE INDEX idx_ficha_necessidade_imediata_ficha   ON ficha_necessidade_imediata (ficha_id);
CREATE INDEX idx_acolhimento_tipo_violencia_acolhimento ON acolhimento_tipo_violencia (acolhimento_id);
CREATE INDEX idx_auth_audit_log_email    ON auth_audit_log (email_tentado);
CREATE INDEX idx_entity_audit_log_entidade ON entity_audit_log (tipo_entidade, entidade_id);
